
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

#use_frameworks!

target 'HYUIKit’ do

	pod 'HYUIKit’, :path => '../'

 	pod 'Masonry'
 	pod 'AFNetworking', '3.2.0'
 
#	pod 'MLeaksFinder'
#   pod 'HYTipView'
# pod 'MarqueeLabel'
#   pod 'FLAnimatedImage', '1.0.12'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
